# Generated by Django 4.1.7 on 2023-02-26 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0004_remove_calchistory_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calchistory",
            name="date",
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="first",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="result",
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="second",
            field=models.IntegerField(default=None),
        ),
    ]
