# Generated by Django 4.1.7 on 2023-02-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("first", "0005_alter_calchistory_date_alter_calchistory_first_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calchistory",
            name="date",
            field=models.DateTimeField(default=0),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="first",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="result",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="calchistory",
            name="second",
            field=models.IntegerField(default=0),
        ),
    ]
